"""empty message

Revision ID: 01012d2da32b
Revises: 428ae02bcebc
Create Date: 2021-01-20 19:35:35.070997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01012d2da32b'
down_revision = '428ae02bcebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Emoji_name', table_name='Emoji')
    op.drop_table('Emoji')
    op.drop_table('EmojiIdToUserId')
    op.add_column('User', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('posersonality_vector', sa.ARRAY(sa.Integer(), dimensions=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'posersonality_vector')
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'display_name')
    op.create_table('EmojiIdToUserId',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('Emoji_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('User_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emoji_id'], ['Emoji.id'], name='EmojiIdToUserId_Emoji_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], name='EmojiIdToUserId_User_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='EmojiIdToUserId_pkey')
    )
    op.create_table('Emoji',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Image_Unicode_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Emoji_pkey')
    )
    op.create_index('ix_Emoji_name', 'Emoji', ['name'], unique=False)
    # ### end Alembic commands ###
