"""empty message

Revision ID: 2292167222a0
Revises: 920447c8bd71
Create Date: 2020-12-10 10:51:23.148529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2292167222a0'
down_revision = '920447c8bd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tribe', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('tribe', sa.Column('slug', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tribe_name'), 'tribe', ['name'], unique=False)
    op.create_unique_constraint(None, 'tribe', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tribe', type_='unique')
    op.drop_index(op.f('ix_tribe_name'), table_name='tribe')
    op.drop_column('tribe', 'slug')
    op.drop_column('tribe', 'name')
    # ### end Alembic commands ###
