"""empty message

Revision ID: 26edc8dbeeca
Revises: 8fe0bd61696b
Create Date: 2021-01-15 12:16:11.654432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26edc8dbeeca'
down_revision = '8fe0bd61696b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tribe', 'posersonality_vector')
    op.add_column('User', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'display_name')
    op.add_column('Tribe', sa.Column('posersonality_vector', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
