"""empty message

Revision ID: 8fe0bd61696b
Revises: 8af6879e92b4
Create Date: 2021-01-01 12:25:08.313843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fe0bd61696b'
down_revision = '8af6879e92b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EmojiIdToUserId')
    op.drop_index('ix_Emoji_name', table_name='Emoji')
    op.drop_table('Emoji')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Emoji',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Image_Unicode_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Emoji_pkey'),
    sa.UniqueConstraint('id', name='Emoji_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_Emoji_name', 'Emoji', ['name'], unique=False)
    op.create_table('EmojiIdToUserId',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('Emoji_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('User_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('Amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Emoji_id'], ['Emoji.id'], name='EmojiIdToUserId_Emoji_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], name='EmojiIdToUserId_User_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='EmojiIdToUserId_pkey'),
    sa.UniqueConstraint('id', name='EmojiIdToUserId_id_key')
    )
    # ### end Alembic commands ###
