"""empty message

Revision ID: 920447c8bd71
Revises: 12b36a3c7841
Create Date: 2020-12-09 22:40:33.190231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '920447c8bd71'
down_revision = '12b36a3c7841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tribe', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('tribe_Id_key', 'tribe', type_='unique')
    op.create_unique_constraint(None, 'tribe', ['id'])
    op.drop_column('tribe', 'Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tribe', sa.Column('Id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tribe', type_='unique')
    op.create_unique_constraint('tribe_Id_key', 'tribe', ['Id'])
    op.drop_column('tribe', 'id')
    # ### end Alembic commands ###
