"""empty message

Revision ID: d6d90c91e60a
Revises: 8fe0bd61696b
Create Date: 2021-01-07 10:36:53.670623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d90c91e60a'
down_revision = '8fe0bd61696b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tribe', sa.Column('posersonality_vector', sa.ARRAY(sa.Integer(), dimensions=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tribe', 'posersonality_vector')
    # ### end Alembic commands ###
