"""empty message

Revision ID: ff1c6a5bba9a
Revises: 01012d2da32b
Create Date: 2021-01-20 19:42:16.379147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1c6a5bba9a'
down_revision = '01012d2da32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('posersonality_vector', sa.ARRAY(sa.Integer(), dimensions=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'posersonality_vector')
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'display_name')
    # ### end Alembic commands ###
